---
version: '3.8'
services:
  flask-app:
    container_name: "flask-app"
    restart: "no"
    image: "flask-app:${IMAGE_TAG}"
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=test
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
