---
name: Pipeline
on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint with yamllint
        run: |
          make yamllint .

  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          make flake8

  pydocstyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pydocstyle
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle

      - name: Lint with pydocstyle
        run: |
          make pydocstyle

  build:
    needs: [flake8, pydocstyle, yamllint]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: flask-app:latest
          outputs: type=docker,dest=/tmp/flask-app.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: flask-app
          path: /tmp/flask-app.tar

  integration-tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: flask-app
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/flask-app.tar
          docker image ls -a

      - name: Run integration tests
        run: |
          make integration-tests
