---
name: Infrastructure code CICD Pipeline
on: [push]

jobs:
  terraform-misconfiguration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Trivy misconfiguration scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config

          # Directory to scan
          scan-ref: terraform
          format: table
          exit-code: 1
          vuln-type: security-check
          severity: CRITICAL,HIGH
