---
name: Infrastructure code CICD Pipeline
on: [push]

jobs:
  infracost:
  # Infracost shows cloud cost estimates for Terraform.
  # It lets DevOps, SRE and engineers see a cost breakdown and understand
  # costs before making changes, either in the terminal or pull requests.
    # needs: [tfsec]
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      # This instructs the CLI to send cost estimates to Infracost Cloud. Our SaaS product
      # complements the open source CLI by giving teams advanced visibility and controls.
      # The cost estimates are transmitted in JSON format and do not contain any cloud
      # credentials or secrets (see https://infracost.io/docs/faq/ for more information).
      INFRACOST_ENABLE_CLOUD: true
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Checkout the current PR branch.
      - name: Checkout PR branch
        uses: actions/checkout@v2

      # Generate Infracost JSON file
      - name: Generate Infracost cost estimate
        run: |
          infracost breakdown --config-file=terraform/infracost.yml \
                              --format=json \
                              --out-file=/tmp/infracost.json

      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
      - name: Post Infracost comment
        # Ensure this job is skipped when running locally with act
        if: ${{ !env.ACT }}
        run: |
          echo PR PR_NUMBER
          echo ${PR_NUMBER}
          infracost comment github --repo=$GITHUB_REPOSITORY \
                                    --pull-request=${PR_NUMBER} \
                                    --path=/tmp/infracost.json \
                                    --github-token=${GITHUB_TOKEN} \
                                    --behavior=update
